language: python
sudo: true
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
  - sudo apt-get install python-xlib
addons:
  apt:
    packages:
    - libopencv-dev
    - python-opencv

script: nosetests

