language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
virtualenv:
  system_site_packages: true
addons:		
  apt:		
    sources:		
      - ubuntu		
    packages:		
    - libopencv-dev		
    - python-opencv		
    - python-xlib
    - scrot
    
script: nosetests

