language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
addons:
  apt:
    packages:
    - libopencv-dev
    - python-opencv
    - python-xlib
    - python3-xlib

script: nosetests

