language: python
python:
  - "2.7"
  - "3.5"
virtualenv:		
-  system_site_packages: true
install:
  - pip install -r requirements.txt
addons:
  apt:
    sources:
    - ubuntu
    packages:
    - libopencv-dev
    - python-opencv
    - python-xlib

script: nosetests

